### Создать сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Имя",
  "lastName": "Фамилия",
  "department": 1,
  "salary": 1000
}
### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "имя",
  "lastName": "фамилия",
  "department": 3,
  "salary": 3000
}
### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "",
  "lastName": "",
  "department": 4,
  "salary": 2000
}
### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": " ",
  "lastName": " ",
  "department": 2,
  "salary": 4000
}
### Создать сотрудника 5
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": null,
  "lastName": null,
  "department": 1,
  "salary": 5000
}